### ISSUE TITLE
MotifMaker runs using test file but not for my sample

### ISSUE THREAD

**Issue by 123sat** [PacificBiosciences/MotifMaker#13]
Hey folks,
MotifMaker runs fine when I test the program using fasta file and modifications.gff.gz file found in MotifMaker-master\MotifMaker\src\test\resources folder.  Command is as follows:
java -jar MotifMaker-assembly-0.3.0.jar find -f MotifMaker\src\test\resources\Geobacter_metallireducens_gDNA.fasta -g MotifMaker\src\test\resources\modifications.gff.gz -o motifsQV60.csv -m 60

But it does not run for my sample. Following error shows up 
java -jar MotifMaker-assembly-0.3.0.jar find -f MotifMaker\src\test\resources\reference.fasta -g MotifMaker\src\test\resources\bresumodifications.gff.gz -o motifsQV60.csv -m 60

Exception in thread "main" java.util.NoSuchElementException: key not found: unitig_0_quiver
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at com.pacbio.basemods.Reader$.com$pacbio$basemods$Reader$$parseLine$1(MotifMixture.scala:270)
        at com.pacbio.basemods.Reader$$anonfun$loadModificationsFromGff$1.apply(MotifMixture.scala:299)
        at com.pacbio.basemods.Reader$$anonfun$loadModificationsFromGff$1.apply(MotifMixture.scala:299)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.TraversableOnce$FlattenOps$$anon$1.hasNext(TraversableOnce.scala:464)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at scala.collection.AbstractIterator.to(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
        at com.pacbio.basemods.Program$.loadModificationsGff(Program.scala:606)
        at com.pacbio.basemods.Program$.runMotifReport(Program.scala:797)
        at com.pacbio.basemods.Program$.main(Program.scala:921)
        at com.pacbio.basemods.Program.main(Program.scala)

Please help.

Sat

**Comment by natechols** [comment]
Please post an example of a line from the GFF, and an example header from the FASTA file.  By the way, why are you running with files in MotifMaker/src/test/resources?  That's only for automated testing, users shouldn't touch this directory.

**Comment by 123sat** [comment]
Thank you for reply. 
Fasta file header: >unitig_0GGCATGGACTACACCTGCACGGTGCGAAC
I am not sure what do you mean by example of a line from gff file. But I hope this will do.
##gff-version 3
##source ipdSummary.py v2.0
##source-commandline /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/ipdSummary.py -v -W /opt/smrtanalysis/userdata/jobs/016/016584/data/base_mod_contig_ids.txt --methylFraction --identify m6A,m4C --mapQvThreshold 10 --paramsPath /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/algorithm_parameters/2014-09/kineticsTools --numWorkers 20 --summary_h5 /opt/smrtanalysis/userdata/jobs/016/016584/data/temp_kinetics.h5 --gff /opt/smrtanalysis/tmpdir/tmpbxQL0N.gff --csv /opt/smrtanalysis/tmpdir/tmp3vsnwL.csv --reference /opt/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/references/17710_WT_HGAP/sequence/17710_WT_HGAP.fasta /opt/smrtanalysis/userdata/jobs/016/016584/data/aligned_reads.cmp.h5
##sequence-region ref000001 1 3445261
unitig_0_quiver	kinModCall	m6A	1	1	57	+	.	coverage=33;context=NNNNNNNNNNNNNNNNNNNNATTTAGTTCGCGAATCGGCTT;IPDRatio=8.01;frac=0.000;fracLow=0.000;fracUp=0.000;identificationQv=37
unitig_0_quiver	kinModCall	m6A	2	2	59	-	.	coverage=34;context=GAAGCCGATTCGCGAACTAAATNNNNNNNNNNNNNNNNNNN;IPDRatio=10.33;frac=1.000;fracLow=0.842;fracUp=1.000;identificationQv=40
unitig_0_quiver	kinModCall	modified_base	9	9	32	-	.	coverage=60;context=CTGATTCGAAGCCGATTCGCGAACTAAATNNNNNNNNNNNN;IPDRatio=2.48
unitig_0_quiver	kinModCall	m4C	11	11	30	+	.	coverage=

Thank you

**Comment by natechols** [comment]
It looks like the FASTA file has just "unitig_0" as the sequence ID, but the GFF file has "unitig_0_quiver".  If you change one of the files to be consistent with the other it should work.

**Comment by 123sat** [comment]
Thanks a lot. This seems to fix my problem. I'm able to run the program now.
