### ISSUE TITLE
motifMaker reprocess: motif csv not found

### ISSUE THREAD

**Issue by nick-youngblut** [PacificBiosciences/MotifMaker#18]
I'm running `motifMaker reprocess` via:

```
/ebio/abt3_projects/software/bin/smrtlink/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/pacbio/motifmaker/binwrap/motifMaker reprocess --minFraction 0.85           --fasta /ebio/abt3_scratch/nyoungblut/LLMETH_105232212974/faidx/reference.fasta --gff tests/output_JM2/kinetic/ipdSummary/subreads/cov1/MT21.gff           --motifs tests/output_JM2/kinetic/motifMaker/reprocess/subreads/cov1/qv60/MT21.csv --output tests/output_JM2/kinetic/motifMaker/reprocess/subreads/cov1/qv60/MT21.gff
```

...which is generating the following error:

```
Done extracting raw kinetics data
Loading motifs: tests/output_JM2/kinetic/motifMaker/reprocess/subreads/cov1/qv30/MT21.csv
Exception in thread "main" java.io.FileNotFoundException: tests/output_JM2/kinetic/motifMaker/reprocess/subreads/cov1/qv30/MT21.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.pacbio.basemods.MotifUtils$.loadMotifCsv(Program.scala:182)
	at com.pacbio.basemods.Program$.runGffReprocess(Program.scala:736)
	at com.pacbio.basemods.Program$.main(Program.scala:849)
	at com.pacbio.basemods.Program.main(Program.scala)
```

It appears that `motifMaker reprocess` is not actually writing the file `MT21.csv`, and then it errors out when later trying to open that file. 

My environment:

```
Ubuntu 18.04.4

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
htslib                    1.10.2               hd3b49d5_1    bioconda
krb5                      1.17.1               hfafb76e_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_7    conda-forge
libcurl                   7.71.1               hcdd3856_2    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libssh2                   1.9.0                hab1572f_3    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
openjdk                   11.0.1            h516909a_1016    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pbbam                     1.3.0                h5b7e6e0_1    bioconda
pbgcpp                    1.9.0                         0    bioconda
pbmm2                     1.3.0                h56fc30b_1    bioconda
pigz                      2.3.4                hed695b0_1    conda-forge
pilon                     1.23                          2    bioconda
pip                       20.1.1                     py_1    conda-forge
python                    3.8.3           cpython_he5300dc_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.2.0           py38h32f6830_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by natechols** [comment]
The motifs.csv file is *input* for the `reprocess` subcommand, not output - you're supposed to run `motifMaker find` to generate the CSV, then `motifMaker reprocess` to generate the GFF for motif sites.
